version: "3"
services:
  app:
    build: .
    image: "matching_customer_and_partner:latest"
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      RAILS_ENV: development
      POSTGRES_USER: postgres
      POSTGRES_HOST: db
    depends_on:
      - db
  db:
    image: postgres:12.0
    volumes:
      - /var/lib/postgresql/data
