default: &default
  adapter: postgresql
  encoding: unicode
  timeout: 5000

development: &development
  <<: *default
  database: matching_customer_and_partner_development
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  username: <%= ENV['POSTGRES_USER'] %>
  host: <%= ENV['POSTGRES_HOST'] || 'localhost' %>
  port: <%= ENV['POSTGRES_PORT'] || '5432' %>

test: &test
  <<: *default
  database: matching_customer_and_partner_test
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  username: <%= ENV['POSTGRES_USER'] %>
  host: <%= ENV['POSTGRES_HOST'] || 'localhost' %>
  port: <%= ENV['POSTGRES_PORT'] || '5432' %>
